version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: docker build -t penthaizza/lunarproject:site-1.0 ./lunar-site
      - run: docker push penthaizza/lunarproject:site-1.0
  test:
    docker:
      - image: penthaizza/lunarproject:site-1.0
    steps:
      - checkout
      - run: yarn install
      - run: yarn test
workflows:
  version: 2
  build_n_test:
    jobs:
      - build
      - test
