version: 2.0
jobs:
  build:
    docker: 
      - image: penthaizza/lunarproject:site-1.0
    step:
      - checkout
      - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
      - run: cd ./lunar-site
      - run: docker build -t penthaizza/lunarproject:site-1.0 .
      - run: docker push penthaizza/lunarproject:site-1.0
