version: 2
jobs:
  build:
    docker:
      - image: node:9.4.0-alpine
    working_directory: ~/lunar-site/lunar-site
    steps:
      - checkout
      - run: 
          name: Install project lunar-site
          command: yarn install
      - run: ls -a
      # - run:
      #     name: Build project lunar-site
      #     command: yarn build
      # - run:
      #     name: Install project lunar-api
      #     command: cd ./lunar-api | yarn install
      # - run:
      #     name: Build project lunar-api
      #     command: cd ./lunar-api | yarn build
#       - run: 
#           name: test
#           command: echo "This Test Space"
#       - run:
#           name: Build Artifact -> Login to Docker Hub
#           command: docker login -u $DOCKER_USER -p $DOCKER_PASS
#       - run:
#           name: Build Artifact -> Build Dockerfile to image
#           command: docker build -t penthaizza/lunarproject:site-1.0 ./lunar-site | docker build -t penthaizza/lunarproject:api-1.0 ./lunar-api
#       - run:
#           name: Push Docker image to Dockerhub
#           command: docker push penthaizza/lunarproject:site-1.0 | docker push penthaizza/lunarproject:api-1.0
#   deploy:
#     machine: true
#     steps:
#       - run: sudo apt-get update; sudo apt-get install sshpass; 
#              sudo sshpass -p 'centos' ssh -o StrictHostKeyChecking=no  centos@54.255.134.176 "ls -a && sudo docker stop lunar-site && sudo docker rm lunar-site && sudo docker rmi penthaizza/lunarproject:site-1.0 && sudo docker pull penthaizza/lunarproject:site-1.0 && sudo docker run -d -p 3000:3000 --name lunar-site penthaizza/lunarproject:site-1.0"
# workflows:
#   version: 2
#   build-test-deploy:
#     jobs:
#       - build
#       - deploy:
#           requires:
#             - build       