version: 2
jobs:
  build:
    docker:
      - image: node:8.9.4-alpine
    working_directory: ~/project/lunar-site/lunar-site
    steps:
      - checkout
      - run:
          name: Install & Build Project lunar-site
          command: cd lunar-site && yarn install && yarn build
      - run:
          name: Install & Build project lunar-api
          command: cd lunar-api && yarn install && yarn build
      - run: 
          name: Test Project
          command: echo "This Test Space"
      - setup_remote_docker: 
          docker_layer_caching: true
      - run:
          name: Install Docker client
          command: |
            set -x
            VER="17.12.0-ce"
            curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-17.12.0-ce.tgz
            tar -xz -C /tmp -f /tmp/docker-$VER.tgz
            mv /tmp/docker/* /usr/bin
      - run: 
          name: Build and Push Docker image
          command: |
            docker login -u $DOCKER_USER -p $DOCKER_PASS
            docker build -t penthaizza/lunarproject:site-1.0 ./lunar-site
            docker build -t penthaizza/lunarproject:api-1.0 ./lunar-api
            docker push penthaizza/lunarproject:site-1.0
            docker push penthaizza/lunarproject:api-1.0
    #   - run:
    #       name: Build Artifact -> Login to Docker Hub
    #       command: docker login -u $DOCKER_USER -p $DOCKER_PASS
    #   - run:
    #       name: Build Artifact -> Build Dockerfile to image
    #       command: docker build -t penthaizza/lunarproject:site-1.0 ./lunar-site | docker build -t penthaizza/lunarproject:api-1.0 ./lunar-api
    #   - run:
    #       name: Push Docker image to Dockerhub
    #       command: docker push penthaizza/lunarproject:site-1.0 | docker push penthaizza/lunarproject:api-1.0
  deploy:
    machine: true
    steps:
      - run: sudo apt-get update; sudo apt-get install sshpass; 
             sudo sshpass -p 'centos' ssh -o StrictHostKeyChecking=no  centos@54.255.134.176 "ls -a && sudo docker stop lunar-site && sudo docker rm lunar-site && sudo docker rmi penthaizza/lunarproject:site-1.0 && sudo docker pull penthaizza/lunarproject:site-1.0 && sudo docker run -d -p 3000:3000 --name lunar-site penthaizza/lunarproject:site-1.0"
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build       